[hyeseung]
title = "alookso ─ 정혜승 대표"
url = "https://alook.so/users/8OgtK8"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[sooyoung]
title = "alookso ─ 윤수영"
url = "https://alook.so/users/xwVtDZ"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[soventure]
title = "alookso ─ 이재웅"
url = "https://alook.so/users/6mt7oo"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[yozoh]
title = "alookso ─ 신요조"
url = "https://alook.so/users/8Ogtd9"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[janghyeyeong]
title = "alookso ─ 장혜영"
url = "https://alook.so/users/8XGtO0"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[ohyeon]
title = "alookso ─ 권오현"
url = "https://alook.so/users/8YEtX8"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[kwonsuengjun]
title = "alookso ─ 권승준"
url = "https://alook.so/users/q73t5E"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[nobody]
title = "alookso ─ Nobody"
url = "https://alook.so/users/bzntNo"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[taekie]
title = "alookso ─ 한상택"
url = "https://alook.so/users/73tAnn"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[writingmate]
title = "alookso ─ 김지은"
url = "https://alook.so/users/bGDtk8"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[kimjinwoong]
title = "alookso ─ 김진웅"
url = "https://alook.so/users/qKktlq"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[hanseolyi]
title = "alookso ─ 한설이"
url = "https://alook.so/users/xwVteq"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[limyuna]
title = "alookso ─ 임유나"
url = "https://alook.so/users/xZBt7x"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"

[parkjinman]
title = "alookso ─ 박진만"
url = "https://alook.so/users/8r9tZb"
entrySelector = "div.flex.flex-col.break-words.min-w-0.bg-white"
titleSelector = "h5[data-qa='post-title'] a"
linkSelector = "div.flex-auto.mt-2.space-y-2 > h6 > a:nth-child(2)"
contentSelector = "h6 a.trix-content-post-partial div.trix-content.line-clamp-5"
imageSelector = "a div img[data-qa='post-cover']"
waitUntil = "networkidle"
onFail = "stale"
